# Site settings
title: inno.space
email: 
description: > # this means to ignore newlines until "baseurl:"
 Inno.space - Design Factory Mannheim provides the environment for passion-based learning, 
 co- creation across disciplines and industrial cooperation. 
 It facilitates teamwork, making, prototyping, and digital fabrication in an inspiring and open atmosphere.
baseurl: "/innospace-web" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"
